# docker-compose.override.yml
# This file is automatically loaded by docker-compose and overrides settings
# Use this for local development overrides

version: '3.8'

services:
  backend:
    environment:
      # Add port 8080 to allowed origins for local testing
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8080,http://frontend:3000
      
  frontend:
    environment:
      # Ensure frontend knows where to find the backend
      - NEXT_PUBLIC_API_URL=http://localhost:8000