version: '3.9'

services:
  # Backend API
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - FIRESTORE_EMULATOR_HOST=firestore:8080
    volumes:
      - ./backend:/app
    command: poetry run uvicorn main:app --reload --host 0.0.0.0

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: pnpm dev

  # Firestore Emulator
  firestore:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    ports:
      - "8080:8080"
      - "4000:4000"  # Emulator UI
    command: >
      bash -c "
        gcloud config set project re-frame-local &&
        gcloud emulators firestore start --host-port=0.0.0.0:8080
      "

  # FAISS Vector DB (Phase 3+)
  faiss:
    build: ./backend/faiss
    ports:
      - "8001:8001"
    volumes:
      - ./data/faiss:/data