# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        files: ^src/

  - repo: local
    hooks:
      - id: generate-openapi-schema
        name: Generate OpenAPI Schema
        entry: bash -c 'cd backend && LOG_LEVEL=ERROR uv run python -c "from src.main import app; import json; print(json.dumps(app.openapi(), indent=2))" > ../frontend/openapi.json 2>/dev/null && echo "Generated OpenAPI schema ($(wc -l < ../frontend/openapi.json) lines)"'
        language: system
        files: ^(backend/src/.*\.py|backend/pyproject\.toml)$
        pass_filenames: false

  - repo: local
    hooks:
      - id: gitleaks-protect
        name: gitleaks protect (staged)
        entry: bash -c 'gitleaks protect --staged --redact --verbose'
        language: system
        pass_filenames: false
