name: Backend CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  test:
    name: Backend Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: backend
      run: |
        uv sync --all-extras

    - name: Check formatting with black and isort
      working-directory: backend
      run: |
        uv run black --check .
        uv run isort --check-only .

    - name: Lint with ruff
      working-directory: backend
      run: uv run ruff check .

    - name: Type check with mypy
      working-directory: backend
      run: uv run mypy src

    - name: Test with pytest
      working-directory: backend
      run: uv run pytest

    - name: Upload coverage reports
      uses: codecov/codecov-action@v5
      if: matrix.python-version == '3.12'
      with:
        file: ./backend/coverage.xml
        fail_ci_if_error: false
        flags: backend