name: Frontend CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'

env:
  NODE_VERSION: '18.x'
  PNPM_VERSION: '10.11.0'

jobs:
  test:
    name: Frontend Tests
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          cd frontend
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Generate OpenAPI schema from backend
        working-directory: backend
        run: |
          # Install backend dependencies
          pip install uv
          uv sync --all-extras
          # Export OpenAPI schema
          uv run python -c "from src.main import app; import json; print(json.dumps(app.openapi(), indent=2))" > ../frontend/openapi.json

      - name: Generate TypeScript API client
        working-directory: frontend
        run: |
          # Generate the API client from the schema
          pnpm run generate:api

      - name: Run ESLint
        working-directory: frontend
        run: pnpm lint

      - name: Run TypeScript check
        working-directory: frontend
        run: pnpm tsc --noEmit

      - name: Run tests
        working-directory: frontend
        run: pnpm test:ci
        env:
          CI: true

      - name: Build application
        working-directory: frontend
        run: pnpm build

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          flags: frontend