name: PR Checks

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  pr-validation:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check PR title for task ID
      uses: actions/github-script@v7
      with:
        script: |
          const title = context.payload.pull_request.title;
          const taskIdPattern = /^\[(BE|FE|IF|ALL)-\d{3}\]/;
          
          if (!taskIdPattern.test(title)) {
            core.setFailed('PR title must start with a task ID like [BE-001], [FE-002], [IF-003], or [ALL-004]');
          } else {
            console.log(`✓ Valid task ID found in PR title: ${title}`);
          }
    
    - name: Check for linked issues
      uses: actions/github-script@v7
      with:
        script: |
          const body = context.payload.pull_request.body || '';
          const issuePattern = /(closes|fixes|resolves)\s+#\d+/i;
          
          if (!issuePattern.test(body)) {
            console.log('⚠️  Warning: No linked issues found in PR description');
            console.log('Consider linking related issues using "Closes #123" or "Fixes #456"');
          } else {
            console.log('✓ Linked issues found in PR description');
          }

  auto-label:
    name: Auto Label PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Label based on changed files
      uses: actions/labeler@v5
      with:
        configuration-path: .github/labeler.yml

  pr-size:
    name: Check PR Size
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check PR size
      uses: actions/github-script@v7
      with:
        script: |
          const { data: pullRequest } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          
          const additions = pullRequest.additions;
          const deletions = pullRequest.deletions;
          const total = additions + deletions;
          
          let size = 'small';
          if (total > 1000) size = 'large';
          else if (total > 500) size = 'medium';
          
          console.log(`PR size: ${size} (${additions} additions, ${deletions} deletions)`);
          
          if (size === 'large') {
            console.log('⚠️  Warning: This is a large PR. Consider breaking it into smaller, focused changes.');
          }